apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgrest
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kcadorin/infra-takehome
    targetRevision: main
    path: postgrest
  destination:
    server: https://kubernetes.default.svc
    namespace: postgrest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
